#!/usr/bin/env bash

set -euxo pipefail

case "$1" in
    pull)
        # pull images based on docker compose files in /opt
        DOCKER_SOCKET_LOCATION=/dummy docker compose -f /opt/supabase/docker/docker-compose.yml -f /opt/supabase/docker/dev/docker-compose.dev.yml pull
    ;;
    init)
        # create volumes (copy from /opt)
        # create docker-compose overrides
    ;;
    # pull)
    #     docker compose pull
    # ;;
    # up)
    #     docker compose up -d
    # ;;
    # stop)
    #     docker compose down
    # ;;
    # remove)
    #     docker compose down -v --remove-orphans
    # ;;
    *)
        :
esac
